# Generated by Django 3.2.12 on 2022-03-31 23:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20220401_0142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Post',
        ),
    ]
