# Generated by Django 3.2.12 on 2022-04-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_profiles_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='post',
            name='job_title',
            field=models.CharField(default='full stack developer', max_length=50),
        ),
    ]
